# Generated by Django 4.2.4 on 2023-10-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_submission_grader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
